version: '3.1'

services:
  db:
    image: postgres:13.5
    restart: always
    container_name: relatorio_servico_api
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: relatorio_servico
    ports:
      - "5432:5432"