# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13.5
    restart: always
    container_name: entregas
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: entrega
    ports:
      - "5432:5432"